---
# ===========================================================================================
# Title   DrawIO
# Created By: PJ Guibord
# Date 08/31/2022
# Revision: n/a
# Version: 1.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  drawio:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    ports:
      - '${drawio_port1}:8080'
      - '${drawio_port2}:8443'