---
# ===========================================================================================
# Title   M$ Windows
# Created By: PJ Guibord
# Date 01/25/2025
# Revision: n/a
# Version: 1.0
# URL: https://github.com/dockur/windows
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  windows:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - '${webui_port}:8006' # Web Console
      - 3389:3389/tcp # RDP/tcp
      - 3389:3389/udp # RDP/udp
    environment:
      VERSION: "11"
      # CPU_CORES: "4"
      # RAM_SIZE: "8G"
    volumes:
      - '${windows_storge}:/data'
