---
# ===========================================================================================
# Title   Nginx Reverse Proxy
# Created By: PJ Guibord
# Date 09/30/2024
# Revision: n/a
# Version: 1.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  nginx-proxy:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    ports:
      - 80:80
      - 443:443
      - '${nginx_port}:81'
    environment:
      INITIAL_ADMIN_EMAIL: ${nginx_email}
      INITIAL_ADMIN_PASSWORD: ${nginx_admin_pw}
      # =====================================
      # Postgres Config
      POSTGRES_SERVER: ${nginx_db_server}
      POSTGRES_USER: ${nginx_db_un}
      POSTGRES_PASSWORD: ${nginx_db_pw}
      POSTGRES_PORT: ${nginx_db_port}
      POSTGRES_DB: ${nginx_db}
      # - PUID=${PUID}
      # - PGID=${PGID}
      # - TZ=${time_zone}
    volumes:
    - '${nginx_data}:/data'
    - '${nginx_letsencrypt}:/etc/letsencrypt'
