---
# ===========================================================================================
# Title   Nginx Reverse Proxy
# Created By: PJ Guibord
# Date 09/30/2024
# Revision: n/a
# Version: 1.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  nginx-proxy:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    ports:
      - 80:80
      - 443:443
      - '${nginx_port}:81'
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      INITIAL_ADMIN_EMAIL: ${nginx_email}
      INITIAL_ADMIN_PASSWORD: ${nginx_admin_pw}
      DISABLE_IPV6: 'true'
    volumes:
    - '${nginx_data}:/data'
    - '${nginx_letsencrypt}:/etc/letsencrypt'
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
