# ===========================================================================================
# Title   Docker Compose YAML
# Created By: PJ Guibord
# Date 08/31/2022
# Revision: n/a
# Version: 1.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

version: "3"
services:  
# OpenSpeedTest
  openspeedtest:
    container_name: OpenSpeedTest
    image: openspeedtest/latest:latest
    ports:
      - "80:3000"
      - "443:3001"
    restart: unless-stopped
# Pihole - More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: PiHole
    hostname: ${Pi_Hostname}
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: ${Pi_TZ}
      WEBPASSWORD: ${Pi_Pass}
      FTLCONF_LOCAL_IPV4: ${Pi_IP}
      ADMIN_EMAIL: ${Pi_Email}
      PIHOLE_DNS: ${Pi_DNS}
      DHCP_ACTIVE: "false"
      DHCP_ROUTER: ${Pi_DHCP_Router}
    volumes:
     - './pihole_app:/etc/pihole'
     - './dns_config:/etc/dnsmasq.d'    
    restart: unless-stopped

