# ===========================================================================================
# Title   Docker Compose YAML
# Created By: PJ Guibord
# Date 08/31/2022
# Revision: 09/30/2024
# Version: 1.2
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release - OpenSpeedTest - does this work? YES!
#   - 1.1: Added PiHole
#   - 1.1: Added Plex and Nginx
# ===========================================================================================



services:
# OpenSpeedTest
  openspeedtest:
    container_name: openspeedtest
    image: openspeedtest/latest:latest
    restart: unless-stopped
    ports:
      - "80:3000"
      - "443:3001"


# Pihole - More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  pihole:
    container_name: pihole
    hostname: ${Pi_Hostname}
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: ${Global_TZ}
      WEBPASSWORD: ${Pi_Pass}
      FTLCONF_LOCAL_IPV4: ${Pi_IP}
      ADMIN_EMAIL: ${Pi_Email}
      PIHOLE_DNS_: "208.67.222.123;208.67.220.123"
      DHCP_ACTIVE: "false"
      DHCP_ROUTER: ${Pi_DHCP_Router}
    volumes:
     - '${Pi_Data_App}:/etc/pihole'
     - '${Pi_Data_Config}:/etc/dnsmasq.d'


# # Plex
#   plex:
#     container_name: plex
#     image: plexinc/pms-docker:latest
#     restart: unless-stopped
#     ports:
#       - "32400:32400/tcp"
#       - "3005:3005/tcp"
#       - "8324:8324/tcp"
#       - "32469:32469/tcp"
#       - "1900:1900/udp"
#       - "32410:32410/udp"
#       - "32412:32412/udp"
#       - "32413:32413/udp"
#       - "32414:32414/udp"
#     environment:
#       - PUID=${PUID}
#       - PGID=${PGID}
#       - TZ=${Global_TZ}
#       - PLEX_CLAIM=${Plex_Claim}
#       - HOSTNAME=${Plex_Hostname}
#       - ADVERTISE_IP=${Plex_Advertise}
#       - ALLOWED_NETWORKS=${Plex_Allowed_Nets}
#     volumes:
#       - '${Plex_Config}:/config'
#       - '${Plex_Transcode}:/transcode'
#       - '${Plex_Media}:/media'


# Nginx
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8787:80"
    environment:
    - NGINX_HOST=themakerspace.guibord.org
    volumes:
      - '${Nginx_HTML}:/usr/share/nginx/html'
