---
# ===========================================================================================
# Title   Pi-hole
# Created By: PJ Guibord
# Date 01/4/2025
# Revision: n/a
# Version: 1.0
# URL: https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  pihole:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    ports:
      # WebUI
      - ${pihole_port}:80/tcp
      # DNS
      - 53:53/tcp
      - 53:53/udp
    environment:
      TZ: ${time_zone}
      WEBPASSWORD: ${pihole_pass}
      ServerIP: ${pihole_published_ip}
      PIHOLE_DNS_: ${pihole_upstream_dns}
      TEMPERATUREUNIT: f
      WEBUIBOXEDLAYOUT: traditional
      WEBTHEME: "lcars"
      DNSSEC: True
    volumes:
      - '${pihole_config}/etc-pihole:/etc/pihole'
      - '${pihole_config}/etc-dnsmasq.d:/etc/dnsmasq.d'
      # - '${pihole_config}/lighttpd:/etc/lighttpd'