---
# ===========================================================================================
# Title   Mealie
# Created By: PJ Guibord
# Date 09/30/2024
# Revision: 01/12/2025
# Version: 2.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
#   - 2.0: New release of Mealie, migrated database backend to Postgres, added SMTP content
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:
  mealie:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    ports:
      - '${mealie_port}:9000'
    environment:
      DB_ENGINE: postgres
      ALLOW_SIGNUP: false
      TZ: ${time_zone}
      BASE_URL: ${mealie_url}
      PUID: ${PUID}
      PGID: ${PGID}
      DEFAULT_GROUP: Home
      DEFAULT_HOUSEHOLD: Family
      # # =====================================
      # Postgres Config
      POSTGRES_DB: ${mealie_db}
      POSTGRES_USER: ${mealie_db_un}
      POSTGRES_PASSWORD: ${mealie_db_pw}
      POSTGRES_SERVER: ${mealie_db_server}
      POSTGRES_PORT: ${mealie_db_port}
      # =====================================
      # Email Configuration
      SMTP_HOST: ${smtp_host}
      SMTP_PORT: ${smtp_port}
      SMTP_AUTH_STRATEGY: TLS # Options: 'TLS', 'SSL', 'NONE'
      SMTP_FROM_NAME: ${smtp_sender_name}
      SMTP_FROM_EMAIL: ${smtp_sender_email} 
      SMTP_USER: ${smtp_un}
      SMTP_PASSWORD: ${smtp_pw}
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - '${mealie_config}:/app/data/'