---
# ===========================================================================================
# Title:   XMRig Docker Compose File
# Created By: PJ Guibord
# Date 08/27/2026
# Revision: n/a
# Version: 1.0
# URL: 
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:
  xmrig:
    build: .
    image: xmrig-local:v6.26.0
    container_name: xmrig
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/cpu:/dev/cpu
    network_mode: host
    volumes:
      - ./config.json:/etc/xmrig/config.json:ro
    command: ["-c", "/etc/xmrig/config.json"]