---
# ===========================================================================================
# Title   Dockge
# Created By: PJ Guibord
# Date 04/01/2026
# Revision: N/A
# Version: 1.0
# LINKS: 
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:

  dockge:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    networks: 
      - dockge_net
    ports:
      - '${dockge_port}:5001/tcp'
    environment:
      DOCKGE_STACKS_DIR: '/opt/stacks'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

networks:
  dockge_net:
    name: dockge_net
    driver: bridge