---
# ===========================================================================================
# Title:   Guacamole Docker Compose File
# Created By: PJ Guibord
# Date 07/04/2026
# Revision: n/a
# Version: 1.0
# URL: 
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd
    restart: unless-stopped
    user: "988:988"
    volumes:
      - /storage/container_data/guacamole/drive:/drive:rw
      - /storage/container_data/guacamole/record:/record:rw
    networks:
      - guacamole_net

  guacamole-db:
    image: postgres:16
    container_name: guacamole-db
    restart: unless-stopped
    user: "988:988"
    mem_limit: 256m
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: "${GUAC_DB_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /storage/container_data/guacamole/db:/var/lib/postgresql/data:rw
      - /storage/container_data/guacamole/initdb:/docker-entrypoint-initdb.d:ro
    networks:
      - guacamole_net

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    user: "988:988"
    depends_on:
      - guacd
      - guacamole-db
    environment:
      HOME: //tmp
      WEBAPP_CONTEXT: ROOT
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacamole-db
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: "${GUAC_DB_PASSWORD}"
      EXTENSIONS: totp
      GUACAMOLE_HOME: /guacamole_home
    volumes:
      - /storage/container_data/guacamole/home:/guacamole_home:rw
      - /storage/container_data/guacamole/webrecord:/record:rw
    ports:
      - "8280:8080"
    networks:
      - guacamole_net

networks:
  guacamole_net:
    driver: bridge