---
# ===========================================================================================
# Title   NextCloud
# Created By: PJ Guibord
# Date 01/4/2025
# Revision: n/a
# Version: 1.0
# URL: https://github.com/nextcloud/all-in-one/blob/main/compose.yaml
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  nextcloud-redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped

  nextcloud:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    env_file:
       - .env
    depends_on:
      - nextcloud-redis
    ports:
     - '${nextcloud_port}:80'
    environment:
      TZ: America/Denver
      REDIS_HOST: nextcloud-redis
      NEXTCLOUD_ADMIN_USER: ${nextcloud_admin_un}
      NEXTCLOUD_ADMIN_PASSWORD: ${nextcloud_admin_pw}
      NEXTCLOUD_TRUSTED_DOMAINS: ${nextcloud_trusted_domain}
      #=====================================
      # Postgres Config
      POSTGRES_HOST: ${nextcloud_db_server}
      POSTGRES_DB: ${nextcloud_db}
      POSTGRES_USER: ${nextcloud_db_un}
      POSTGRES_PASSWORD: ${nextcloud_db_pw}
      # =====================================
      # Email Configuration
      SMTP_HOST: ${smtp_host}
      SMTP_PORT: ${smtp_port}
      SMTP_SECURE: TLS
      MAIL_FROM_ADDRESS: ${smtp_sender_name}
      MAIL_DOMAIN: ${smtp_sender_email}
      SMTP_NAME: ${smtp_un}
      SMTP_PASSWORD: ${smtp_pw}
    volumes:
      - '${nextcloud_html}:/var/www/html/data/'
      - '${nextcloud_config}:/var/www/html/config/'
      - '${nextcloud_custom_apps_data}:/var/www/html/custom_apps'
