---
# ===========================================================================================
# Title   Collabora/CODE
# Created By: PJ Guibord
# Date 09/30/2024
# Revision: 01/12/2025
# Version: 2.0
# LINKS: https://docs.mealie.io/documentation/getting-started/installation/backend-config/
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
#   - 2.0: New release of Mealie, migrated database backend to Postgres, added SMTP content
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:
  collabora:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    ports:
      - '${collabora_port}:9980'
    environment:
      TZ: ${time_zone}
      dictionaries: 'en_US'
      domain: '${domain}'
      username: '${collabora_username}'
      password: '${collabora_password}'
      extra_params: '${extra_parameters}'
    volumes:
      - '${coolwsd}:/etc/coolwsd/'
      