apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pj-test
  namespace: pj-test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: px-db
  volumeMode: Filesystem
  volumeName: pvc-pj-test