# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: pj-test-postgres-ns

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: ps_db
  POSTGRES_USER: ps_user
  POSTGRES_PASSWORD: SecurePassword

---


# ---
# # PV
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pj-test-postgres-pv
#   namespace: pj-test-postgres-ns
# spec:
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/data"

---
# PVC   
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pj-test-postgres-pvc
  namespace: pj-test-postgres-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi