# ===========================================================================================
# Title   AdGuard Home
# Created By: PJ Guibord
# Date 01/4/2025
# Revision: n/a
# Version: 1.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach


services:
  adguardhome:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    network_mode: host
    ports:
      # WebUI
      - ${adguard_port1}:3000/tcp
      # DNS
      - 53:53/tcp
      # HTTPS/DNS-over-HTTPS
      - 443:443/tcp
      # DNS-over-TLS
      - 853:853/tcp
      # DNS-over-QUIC
      - 853:853/udp
      # DNSCrypt
      - 5443:5443/tcp
      - 5443:5443/udp
      # # DHCP server
      # - 67:67/udp
      # - 68:68/udp
    volumes:
      - '${adguard_config}/db:/opt/adguardhome/work'
      - '${adguard_config}/conf:/opt/adguardhome/conf'