---
# ===========================================================================================
# Title   Apache
# Created By: PJ Guibord
# Date 09/20/2024
# Revision: 01/04/2025
# Version: 1.1
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
#   - 1.1: Added health check
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:
  website0:
    container_name: ${container_name0}
    image:  ${image}
    restart: unless-stopped
    networks: 
      - apache_net
    ports:
    - '${apache_site0_port}:80'
    volumes:
      - '${apache_site0_html}:/usr/local/apache2/htdocs/'

  website1:
    container_name: ${container_name1}
    image:  ${image}
    restart: unless-stopped
    networks: 
      - apache_net
    ports:
    - '${apache_site1_port}:80'
    volumes:
      - '${apache_site1_html}:/usr/local/apache2/htdocs/'

  website2:
    container_name: ${container_name2}
    image:  ${image}
    restart: unless-stopped
    networks: 
      - apache_net
    ports:
    - '${apache_site2_port}:80'
    volumes:
      - '${apache_site2_html}:/usr/local/apache2/htdocs/'
  
  website3:
    container_name: ${container_name3}
    image:  ${image}
    restart: unless-stopped
    networks: 
      - apache_net
    ports:
    - '${apache_site3_port}:80'
    volumes:
      - '${apache_site3_html}:/usr/local/apache2/htdocs/'

networks:
  apache_net:
    name: apache_net
    driver: bridge