# ===========================================================================================
# Title   Mealie
# Created By: PJ Guibord
# Date 09/30/2024
# Revision: n/a
# Version: 1.0
# ===========================================================================================
# Revision History:
#   - 1.0: Initial Release
# ===========================================================================================

# docker run -p <HostPort:containerport> imagename:tag

# Start containers:: 
#   docker compose up --detach

services:
  keepassxc:
    container_name: ${container_name}
    image: ${image}
    restart: unless-stopped
    ports:
      - '${keypassxc_port1}:3000'
      - '${keypassxc_port2}:3001'
    security_opt:
      - seccomp:unconfined #optional
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${time_zone}
    volumes:
      - '${keepassxc_config}:/config'